name: lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run lint with black, isort, ruff
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install -r requirements-test.lock
      - name: Lint with black
        run: black . --check
      - name: Lint with isort
        run: isort . --check-only
      - name: Lint with ruff
        run: ruff .
